name: fatiando-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - xarray
  - netcdf4
  - pyproj
  - pykdtree
  # for LIDAR data
  - laspy
  - laszip # the C lib
  - pip:
    - laszip # the Python bindinds
  # For reading xlsx files
  - openpyxl
  # Fatiando
  - pooch>=1.0
  - harmonica==0.4.*
  - verde==1.6.1
  - boule==0.3.*
  # GMT for plotting
  - pygmt==0.4.1
  - gmt==6.2.0
